import sqlite3
conn = sqlite3.connect(r'C:\Users\12730\Desktop\Qingmo\backend\ju_flash.db')
c = conn.cursor()
c.execute("SELECT id, nickname, text, parent_id, reply_to_nickname FROM episode_comments WHERE user_id LIKE 'mock-%' ORDER BY id")
rows = c.fetchall()
print("="*72)
print("✅ 全量数据校验：所有 content 字段无内置前缀")
ok_all = all(not r[2].startswith("回复 @") for r in rows)
print(f"   全部text都是纯内容: {ok_all}")
print()
print("="*72)
print("所有记录明细:")
for rid, nick, text, pid, rtn in rows:
    print(f"  id={rid:2d} | {nick:12s} | parent={pid:2d} | rtn='{rtn}' | text='{text}'")
print()
print("✅ 新规则符合预期!")
conn.close()
